---
title: "R/COMA"
author: Jeffrey Endelman
output: github_document
---

Plant and animal breeders have long appreciated the need to balance selection for short-term genetic gain with maintaining genetic variance for long-term gain. The COMA package implements selection strategies known as Optimal Contribution Selection (OCS) and Optimal Mate Allocation (OMA) in the animal breeding literature. In both cases, the optimal strategy maximizes the genetic merit of the F1 progeny while restricting the inbreeding rate and potentially other constraints. In OCS, the decision variables are the genetic contributions of the parents, but a specific mating plan is not developed-- the objective function assumes random mating. In OMA, the contribution (i.e., allocation) of each mating is also specified. The "C" in COMA stands for Convex because the software exploits the convex nature of the problem to efficiently find the global optimum. 

Financial support for developing COMA has come from the USDA National Institute of Food and Agriculture (NIFA) Award 2020-51181-32156. A manuscript describing the methods is in preparation.  [Vignette 1](https://jendelman.github.io/COMA/Vignette1.html) provides examples of using the software with data from the University of Wisconsin-Madison potato breeding program.

To install and load the package:
```R
install.packages("devtools")
devtools::install_github("jendelman/COMA", build_vignettes=FALSE)
library(COMA)
```

For a complete specification of package functions, consult the [reference manual.](https://jendelman.github.io/COMA/manual.pdf)



